### ISSUE TITLE
Use appAddr instead of universal channel port

### ISSUE THREAD

**Issue by mvpoyatt** [polymerdao/ibc-explorer#27]
Description
------------
-  In packets table use the appAddr instead of the universal channel port

Reasoning
----------
- Gather more info from @tmsdkeys

**Comment by tmsdkeys** [comment]
In addition to displaying the relevant address (the application on src and dest rather than the universal channel handler) it might also be good to show the events and/or transactions to be those from the universal channel handler?

I.e. [these events](https://github.com/open-ibc/vibc-core-smart-contracts/blob/main/contracts/interfaces/IbcMiddleware.sol#L127-L166) that are currently not implemented on the UC handler...
